# This workflow automatically creates a release PR for the CI integration.

name: Bump Datadog CI

on:
  workflow_dispatch:
    inputs:
      datadog_ci_version:
        description: "Version of datadog-ci to install (`latest` or `A.B.C`)"
        type: string
        default: "latest"

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-datadog-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Blah
        run: |
          echo "https://github.com/DataDog/datadog-ci/actions/runs/${{ github.run_id }}"
