name: On Release PR merged
on:
  pull_request:
    types:
      - closed

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR ${{ toJSON(github.event) }} has been merged
