# This workflow automatically updates release PRs when more changes were pushed on them.

name: Update Release PR

on:
  push:
    branches:
      - "release/**"

jobs:
  update-release-pull-request:
    runs-on: ubuntu-latest
    steps:
      # Do the changes again
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Set git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Install dependencies
        run: yarn install
      - name: Update build files
        run: yarn build && yarn package
      - name: Amend version commit
        id: amend-version-commit
        run: |
          VERSION_TAG=$(echo ${GITHUB_REF#refs/heads/release/}) 
          git commit --all --amend --no-edit
          git tag --force $VERSION_TAG
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_OUTPUT
      - name: Push the branch (with tags)
        run: git push --follow-tags -u origin local-branch:release/${{ steps.amend-version-commit.outputs.VERSION_TAG }}

      # Create the pull request
      - name: Generate release notes
        id: generate-release-notes
        uses: actions/github-script@v6
        with:
          script: |
            const { data: releaseNotes } = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ steps.amend-version-commit.outputs.VERSION_TAG }}',
            })

            return releaseNotes.body
      - name: Create pull request
        id: create-pull-request
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'main',
              head: 'release/${{ steps.amend-version-commit.outputs.VERSION_TAG }}',
              title: '[release:${{ github.event.inputs.semver }}] `${{ steps.amend-version-commit.outputs.VERSION_TAG }}`',
              body: ${{ steps.generate-release-notes.outputs.result }}
            })

            return pullRequest.number
      - name: Create comment
        uses: actions/github-script@v6
        with:
          script: |
            const body = require('./ci/release-pr-comment')

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{steps.create-pull-request.outputs.result}},
              body
            })
